import type { GamePreview, SlateGame, Snapshot } from "../types";

export const mockSlate: SlateGame[] = [
  {
    gameId: "gsw-dal-demo",
    status: "scheduled",
    tipoff: "7:30 PM ET",
    broadcast: "ESPN",
    arena: "Chase Center",
    headline: "Ball-screen chess between Luka's usage and Kerr's coverage counters.",
    homeTeam: "Golden State Warriors",
    awayTeam: "Dallas Mavericks",
    homeAbbreviation: "GSW",
    awayAbbreviation: "DAL",
    homeRecord: "46-36",
    awayRecord: "50-32",
    predictionHook:
      "Luka is the leverage point, and BallPredict expects Golden State to escalate ball pressure if his usage spikes early.",
  },
  {
    gameId: "bos-lal-demo",
    status: "scheduled",
    tipoff: "8:00 PM ET",
    broadcast: "ABC",
    arena: "Crypto.com Arena",
    headline: "Five-out spacing pressure against a star-driven interior matchup.",
    homeTeam: "Los Angeles Lakers",
    awayTeam: "Boston Celtics",
    homeAbbreviation: "LAL",
    awayAbbreviation: "BOS",
    homeRecord: "44-38",
    awayRecord: "58-24",
    predictionHook:
      "Boston's spacing profile forces the Lakers into tougher weak-side decisions and sharper rotation discipline.",
  },
  {
    gameId: "den-phx-demo",
    status: "scheduled",
    tipoff: "10:00 PM ET",
    broadcast: "TNT",
    arena: "Footprint Center",
    headline: "Jokic hub offense against midrange shotmaking and late-switch counters.",
    homeTeam: "Phoenix Suns",
    awayTeam: "Denver Nuggets",
    homeAbbreviation: "PHX",
    awayAbbreviation: "DEN",
    homeRecord: "45-37",
    awayRecord: "54-28",
    predictionHook:
      "Denver's cutting and post facilitation create the biggest coaching stress test on the slate.",
  },
];

export const mockPreview: GamePreview = {
  gameId: "gsw-dal-demo",
  status: "scheduled",
  tipoff: "7:30 PM ET",
  broadcast: "ESPN",
  arena: "Chase Center",
  headline: "Ball-screen chess between Luka's usage and Kerr's coverage counters.",
  homeTeam: {
    teamId: "gsw",
    teamName: "Golden State Warriors",
    coachName: "Steve Kerr",
    offensiveRating: 117.3,
    defensiveRating: 113.9,
    pace: 101.4,
    threePointRate: 0.47,
    benchDepth: 0.58,
  },
  awayTeam: {
    teamId: "dal",
    teamName: "Dallas Mavericks",
    coachName: "Jason Kidd",
    offensiveRating: 118.9,
    defensiveRating: 114.8,
    pace: 99.8,
    threePointRate: 0.43,
    benchDepth: 0.51,
  },
  playersToWatch: [
    {
      playerId: "luka",
      playerName: "Luka Doncic",
      teamId: "dal",
      usageRate: 0.39,
      momentumScore: 0.68,
      fatigueIndex: 0.14,
      matchupDifficulty: 0.44,
    },
    {
      playerId: "kai",
      playerName: "Kyrie Irving",
      teamId: "dal",
      usageRate: 0.28,
      momentumScore: 0.61,
      fatigueIndex: 0.12,
      matchupDifficulty: 0.49,
    },
    {
      playerId: "steph",
      playerName: "Stephen Curry",
      teamId: "gsw",
      usageRate: 0.31,
      momentumScore: 0.62,
      fatigueIndex: 0.12,
      matchupDifficulty: 0.58,
    },
    {
      playerId: "jimmy",
      playerName: "Jimmy Butler",
      teamId: "gsw",
      usageRate: 0.27,
      momentumScore: 0.55,
      fatigueIndex: 0.17,
      matchupDifficulty: 0.54,
    },
  ],
  gameFactors: ["pace pressure", "lineup staggering", "half-court shot creation", "weak-side help timing", "rest advantage"],
  predictionSummary:
    "Luka is the primary leverage point. BallPredict expects Steve Kerr to adjust shell help, screen coverage, and rotation staggering around that usage load.",
};

export const mockSnapshot: Snapshot = {
  gameId: "gsw-dal-demo",
  quarter: 0,
  clock: "12:00",
  homeTeam: {
    teamId: "gsw",
    teamName: "Golden State Warriors",
    finalScoreMean: 114,
    finalScoreCI: [107, 122],
    pace: 102.6,
    offensiveRating: 118.1,
    defensiveRating: 112.6,
    winProbability: 0.44,
    projectedScore: [29, 27, 28, 30],
  },
  awayTeam: {
    teamId: "dal",
    teamName: "Dallas Mavericks",
    finalScoreMean: 117,
    finalScoreCI: [111, 125],
    pace: 100.7,
    offensiveRating: 119.2,
    defensiveRating: 111.8,
    winProbability: 0.56,
    projectedScore: [29, 30, 28, 30],
  },
  playerProjections: [
    {
      playerId: "luka",
      playerName: "Luka Doncic",
      teamId: "dal",
      momentumScore: 0.68,
      fatigueIndex: 0.14,
      defensivePressure: 0.66,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 31.8, assists: 9.4, rebounds: 8.2, threesMade: 3.6, turnovers: 4.1, usageRate: 0.35, fieldGoalPct: 0.51 } },
      adjustments: [
        {
          title: "Blitz Primary Action",
          side: "defense",
          trigger: "Luka is the primary high-usage initiator entering the game",
          explanation: "Golden State projects to send extra bodies to the ball if Luka wins the first quarter touch battle.",
          counters: ["trap at level", "weak-side tag", "scram switch on short roll"],
          impact: { field_goal_pct: -0.05, assists: 0.8, turnovers: 0.6 },
        },
        {
          title: "Shrink the Floor",
          side: "defense",
          trigger: "Paint pressure is bending the shell",
          explanation: "The Warriors are loading nail help and icing side pick-and-rolls to cut off downhill lanes.",
          counters: ["nail help", "ICE side pick-and-roll", "gap shrink"],
          impact: { field_goal_pct: -0.03, skip_pass_frequency: 0.08 },
        },
      ],
    },
    {
      playerId: "steph",
      playerName: "Stephen Curry",
      teamId: "gsw",
      momentumScore: 0.62,
      fatigueIndex: 0.12,
      defensivePressure: 0.58,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 28.7, assists: 6.8, rebounds: 4.6, threesMade: 4.8, turnovers: 3.2, usageRate: 0.31, fieldGoalPct: 0.47 } },
      adjustments: [
        {
          title: "Top-Lock Off-Ball Actions",
          side: "defense",
          trigger: "Movement shooting gravity is stretching help",
          explanation: "Dallas is top-locking off-ball screens and pre-switching larger bodies into movement actions.",
          counters: ["top-lock", "lock-and-trail", "pre-switch into pindown"],
          impact: { three_point_pct: -0.04, secondary_handler_usage: 0.05 },
        },
      ],
    },
  ],
  insights: [
    {
      title: "Primary Defensive Shift",
      body: "BallPredict expects Dallas's primary creation burden to trigger more help-side pressure and push the offense toward corner and slot kickout creation.",
      severity: "warning",
    },
    {
      title: "Fatigue Watch",
      body: "Lead creators are carrying above-normal touch loads, which raises turnover variance in late-clock possessions.",
      severity: "info",
    },
    {
      title: "Bench Leverage Edge",
      body: "Golden State's second unit projects better defensively if the game slows into half-court possessions.",
      severity: "advantage",
    },
  ],
  possessionFeed: [
    { quarter: 1, clock: "12:00", summary: "Pregame modeling expects Golden State to ICE side pick-and-rolls and crowd the nail early.", leverage: "high" },
    { quarter: 2, clock: "08:30", summary: "Dallas counters with ghost screens to drag the low man away and reopen slot passing windows.", leverage: "medium" },
    { quarter: 4, clock: "04:10", summary: "A projected scram switch package protects smaller guards during closing mismatch hunts.", leverage: "medium" },
  ],
  winProbabilitySeries: [
    { minute: 0, home: 0.53, away: 0.47 },
    { minute: 4, home: 0.5, away: 0.5 },
    { minute: 8, home: 0.46, away: 0.54 },
    { minute: 12, home: 0.42, away: 0.58 },
    { minute: 16, home: 0.45, away: 0.55 },
    { minute: 20, home: 0.44, away: 0.56 },
    { minute: 24, home: 0.44, away: 0.56 },
    { minute: 28, home: 0.47, away: 0.53 },
    { minute: 32, home: 0.49, away: 0.51 },
    { minute: 36, home: 0.46, away: 0.54 },
    { minute: 40, home: 0.43, away: 0.57 },
    { minute: 44, home: 0.44, away: 0.56 },
    { minute: 48, home: 0.44, away: 0.56 },
  ],
};
