/**
 * Fallback data used only when the backend is unreachable.
 * All projected stats are 0 — projections are computed server-side.
 * Rosters reflect the 2024-25 NBA season (Luka Doncic traded to LAL Feb 2025).
 */
import type { GamePreview, PlayerDetail, SlateGame, Snapshot } from "../types";

function completeMockRoster(players: any[]) {
  return players.map((player) => ({
    rotationRole: "bench",
    availabilityStatus: "available",
    dnpReason: null,
    ...player,
  }));
}

export const mockSlate: SlateGame[] = [
  {
    gameId: "lal-gsw-demo",
    status: "scheduled",
    tipoff: "7:30 PM ET",
    broadcast: "ESPN",
    arena: "Crypto.com Arena",
    headline: "Lakers vs Warriors — connect to the server for live data.",
    homeTeam: "Los Angeles Lakers",
    awayTeam: "Golden State Warriors",
    homeAbbreviation: "LAL",
    awayAbbreviation: "GSW",
    homeRecord: "--",
    awayRecord: "--",
    predictionHook: "Live game data unavailable. Start the backend server to load today's NBA slate.",
  },
];

export const mockPreview: GamePreview = {
  gameId: "lal-gsw-demo",
  status: "scheduled",
  tipoff: "7:30 PM ET",
  broadcast: "ESPN",
  arena: "Crypto.com Arena",
  headline: "Lakers vs Warriors — connect to the server for live data.",
  homeTeam: {
    teamId: "lal",
    teamName: "Los Angeles Lakers",
    coachName: "JJ Redick",
    offensiveRating: 114.0,
    defensiveRating: 114.0,
    pace: 98.0,
    threePointRate: 0.39,
    benchDepth: 0.50,
  },
  awayTeam: {
    teamId: "gsw",
    teamName: "Golden State Warriors",
    coachName: "Steve Kerr",
    offensiveRating: 114.0,
    defensiveRating: 114.0,
    pace: 98.0,
    threePointRate: 0.42,
    benchDepth: 0.50,
  },
  playersToWatch: [
    {
      playerId: "luka",
      playerName: "Luka Doncic",
      teamId: "lal",
      usageRate: 0.35,
      momentumScore: 0.65,
      fatigueIndex: 0.15,
      matchupDifficulty: 0.50,
    },
    {
      playerId: "ad",
      playerName: "Anthony Davis",
      teamId: "lal",
      usageRate: 0.28,
      momentumScore: 0.60,
      fatigueIndex: 0.18,
      matchupDifficulty: 0.55,
    },
    {
      playerId: "steph",
      playerName: "Stephen Curry",
      teamId: "gsw",
      usageRate: 0.31,
      momentumScore: 0.62,
      fatigueIndex: 0.12,
      matchupDifficulty: 0.55,
    },
  ],
  gameFactors: ["pace pressure", "lineup staggering", "half-court shot creation", "weak-side help timing", "rest advantage"],
  predictionSummary: "Backend server is offline. Start the server to load live NBA data and projections.",
};

const _zeroStats = {
  points: 0,
  assists: 0,
  rebounds: 0,
  threesMade: 0,
  turnovers: 0,
  usageRate: 0,
  fieldGoalPct: 0,
};

export const mockSnapshot: Snapshot = {
  gameId: "lal-gsw-demo",
  quarter: 0,
  clock: "12:00",
  homeTeam: {
    teamId: "lal",
    teamName: "Los Angeles Lakers",
    score: 0,
    finalScoreMean: 0,
    finalScoreCI: [0, 0],
    pace: 98.0,
    offensiveRating: 114.0,
    defensiveRating: 114.0,
    winProbability: 0.5,
    projectedScore: [0, 0, 0, 0],
  },
  awayTeam: {
    teamId: "gsw",
    teamName: "Golden State Warriors",
    score: 0,
    finalScoreMean: 0,
    finalScoreCI: [0, 0],
    pace: 98.0,
    offensiveRating: 114.0,
    defensiveRating: 114.0,
    winProbability: 0.5,
    projectedScore: [0, 0, 0, 0],
  },
  playerProjections: completeMockRoster([
    {
      playerId: "luka",
      playerName: "Luka Doncic",
      teamId: "lal",
      rotationRole: "starter",
      momentumScore: 0.65,
      fatigueIndex: 0.15,
      defensivePressure: 0.55,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: _zeroStats },
      adjustments: [],
    },
    {
      playerId: "ad",
      playerName: "Anthony Davis",
      teamId: "lal",
      momentumScore: 0.60,
      fatigueIndex: 0.18,
      defensivePressure: 0.50,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: _zeroStats },
      adjustments: [],
    },
    {
      playerId: "steph",
      playerName: "Stephen Curry",
      teamId: "gsw",
      rotationRole: "starter",
      momentumScore: 0.62,
      fatigueIndex: 0.12,
      defensivePressure: 0.52,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: _zeroStats },
      adjustments: [],
    },
    {
      playerId: "looney",
      playerName: "Kevon Looney",
      teamId: "gsw",
      momentumScore: 0.34,
      fatigueIndex: 0.12,
      defensivePressure: 0.28,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 6.1, assists: 1.7, rebounds: 6.8, threesMade: 0, turnovers: 0.9, usageRate: 0.09, fieldGoalPct: 0.57 } },
      adjustments: [],
    },
    {
      playerId: "moody",
      playerName: "Moses Moody",
      teamId: "gsw",
      momentumScore: 0.36,
      fatigueIndex: 0.11,
      defensivePressure: 0.30,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 7.8, assists: 1.2, rebounds: 2.9, threesMade: 1.5, turnovers: 0.8, usageRate: 0.1, fieldGoalPct: 0.44 } },
      adjustments: [],
    },
    {
      playerId: "kuminga",
      playerName: "Jonathan Kuminga",
      teamId: "gsw",
      momentumScore: 0.4,
      fatigueIndex: 0.11,
      defensivePressure: 0.35,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 10.2, assists: 1.8, rebounds: 4.1, threesMade: 0.7, turnovers: 1.3, usageRate: 0.12, fieldGoalPct: 0.48 } },
      adjustments: [],
    },
    {
      playerId: "santos",
      playerName: "Gui Santos",
      teamId: "gsw",
      momentumScore: 0.28,
      fatigueIndex: 0.1,
      defensivePressure: 0.2,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 4.4, assists: 0.8, rebounds: 2.5, threesMade: 0.6, turnovers: 0.6, usageRate: 0.06, fieldGoalPct: 0.43 } },
      adjustments: [],
    },
    {
      playerId: "spencer",
      playerName: "Pat Spencer",
      teamId: "gsw",
      momentumScore: 0.2,
      fatigueIndex: 0.09,
      defensivePressure: 0.18,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 2.1, assists: 1.0, rebounds: 1.1, threesMade: 0.2, turnovers: 0.5, usageRate: 0.03, fieldGoalPct: 0.4 } },
      adjustments: [],
    },
    {
      playerId: "post",
      playerName: "Quinten Post",
      teamId: "gsw",
      momentumScore: 0.22,
      fatigueIndex: 0.09,
      defensivePressure: 0.19,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 3.6, assists: 0.7, rebounds: 2.4, threesMade: 0.5, turnovers: 0.4, usageRate: 0.04, fieldGoalPct: 0.42 } },
      adjustments: [],
    },
    {
      playerId: "payton",
      playerName: "Gary Payton II",
      teamId: "gsw",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Coach's Decision",
      momentumScore: 0.1,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "jackson-davis",
      playerName: "Trayce Jackson-Davis",
      teamId: "gsw",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Coach's Decision",
      momentumScore: 0.1,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "waters",
      playerName: "Lindy Waters III",
      teamId: "gsw",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Inactive",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "slomo",
      playerName: "Kyle Anderson",
      teamId: "gsw",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Inactive",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "marshall",
      playerName: "Naji Marshall",
      teamId: "dal",
      momentumScore: 0.35,
      fatigueIndex: 0.11,
      defensivePressure: 0.31,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 8.6, assists: 1.7, rebounds: 4.2, threesMade: 0.9, turnovers: 1.0, usageRate: 0.1, fieldGoalPct: 0.46 } },
      adjustments: [],
    },
    {
      playerId: "lively",
      playerName: "Dereck Lively II",
      teamId: "dal",
      momentumScore: 0.31,
      fatigueIndex: 0.12,
      defensivePressure: 0.28,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 7.9, assists: 1.2, rebounds: 6.4, threesMade: 0, turnovers: 0.9, usageRate: 0.09, fieldGoalPct: 0.62 } },
      adjustments: [],
    },
    {
      playerId: "hardy",
      playerName: "Jaden Hardy",
      teamId: "dal",
      momentumScore: 0.29,
      fatigueIndex: 0.1,
      defensivePressure: 0.25,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 6.4, assists: 1.3, rebounds: 1.9, threesMade: 1.1, turnovers: 0.8, usageRate: 0.08, fieldGoalPct: 0.43 } },
      adjustments: [],
    },
    {
      playerId: "powell",
      playerName: "Dwight Powell",
      teamId: "dal",
      momentumScore: 0.21,
      fatigueIndex: 0.1,
      defensivePressure: 0.2,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 3.1, assists: 0.8, rebounds: 2.6, threesMade: 0, turnovers: 0.5, usageRate: 0.04, fieldGoalPct: 0.55 } },
      adjustments: [],
    },
    {
      playerId: "martin",
      playerName: "Caleb Martin",
      teamId: "dal",
      momentumScore: 0.27,
      fatigueIndex: 0.1,
      defensivePressure: 0.24,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 5.9, assists: 1.1, rebounds: 3.3, threesMade: 1.0, turnovers: 0.7, usageRate: 0.07, fieldGoalPct: 0.42 } },
      adjustments: [],
    },
    {
      playerId: "dinwiddie",
      playerName: "Spencer Dinwiddie",
      teamId: "dal",
      momentumScore: 0.3,
      fatigueIndex: 0.1,
      defensivePressure: 0.27,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 7.1, assists: 2.9, rebounds: 2.2, threesMade: 1.2, turnovers: 1.0, usageRate: 0.08, fieldGoalPct: 0.41 } },
      adjustments: [],
    },
    {
      playerId: "exum",
      playerName: "Dante Exum",
      teamId: "dal",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Injury Management",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "christie",
      playerName: "Max Christie",
      teamId: "dal",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Coach's Decision",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "omax",
      playerName: "Olivier-Maxence Prosper",
      teamId: "dal",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Coach's Decision",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "lawson",
      playerName: "A.J. Lawson",
      teamId: "dal",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Inactive",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "edwards",
      playerName: "Kessler Edwards",
      teamId: "dal",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Inactive",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
  ]),
  insights: [
    {
      title: "Backend Offline",
      body: "Start the backend server to load today's real NBA games, live scores, and player stats.",
      severity: "warning",
    },
  ],
  possessionFeed: [],
  winProbabilitySeries: [{ minute: 0, home: 0.5, away: 0.5 }],
};

export const mockPlayerDetail: PlayerDetail = {
  gameId: "lal-gsw-demo",
  playerId: "luka",
  playerName: "Luka Doncic",
  teamId: "lal",
  teamName: "Los Angeles Lakers",
  opponentTeamName: "Golden State Warriors",
  coachCounterSummary: "Live data unavailable — start the backend server to load projections.",
  projection: mockSnapshot.playerProjections[0],
  quarterBreakdown: [
    { quarter: "Q1", points: 0, assists: 0, rebounds: 0, threesMade: 0 },
    { quarter: "Q2", points: 0, assists: 0, rebounds: 0, threesMade: 0 },
    { quarter: "Q3", points: 0, assists: 0, rebounds: 0, threesMade: 0 },
    { quarter: "Q4", points: 0, assists: 0, rebounds: 0, threesMade: 0 },
  ],
  statProfile: [
    { label: "Points", live: 0, projected: 0 },
    { label: "Assists", live: 0, projected: 0 },
    { label: "Rebounds", live: 0, projected: 0 },
    { label: "3PM", live: 0, projected: 0 },
    { label: "Turnovers", live: 0, projected: 0 },
  ],
  matchupFactors: ["Live data unavailable"],
  confidence: { floorPoints: 0, medianPoints: 0, ceilingPoints: 0, pressure: 0.5 },
  playerInsights: [
    {
      title: "Backend Offline",
      body: "Start the backend server to load today's real NBA games, rosters, and live scores.",
      severity: "warning",
    },
  ],
};
