import type { GamePreview, PlayerDetail, SlateGame, Snapshot } from "../types";

function completeMockRoster(players: any[]) {
  return players.map((player) => ({
    rotationRole: "bench",
    availabilityStatus: "available",
    dnpReason: null,
    ...player,
  }));
}

export const mockSlate: SlateGame[] = [
  {
    gameId: "gsw-dal-demo",
    status: "scheduled",
    tipoff: "7:30 PM ET",
    broadcast: "ESPN",
    arena: "Chase Center",
    headline: "Ball-screen chess between Luka's usage and Kerr's coverage counters.",
    homeTeam: "Golden State Warriors",
    awayTeam: "Dallas Mavericks",
    homeAbbreviation: "GSW",
    awayAbbreviation: "DAL",
    homeRecord: "46-36",
    awayRecord: "50-32",
    predictionHook:
      "Luka is the leverage point, and BallPredict expects Golden State to escalate ball pressure if his usage spikes early.",
  },
  {
    gameId: "bos-lal-demo",
    status: "scheduled",
    tipoff: "8:00 PM ET",
    broadcast: "ABC",
    arena: "Crypto.com Arena",
    headline: "Five-out spacing pressure against a star-driven interior matchup.",
    homeTeam: "Los Angeles Lakers",
    awayTeam: "Boston Celtics",
    homeAbbreviation: "LAL",
    awayAbbreviation: "BOS",
    homeRecord: "44-38",
    awayRecord: "58-24",
    predictionHook:
      "Boston's spacing profile forces the Lakers into tougher weak-side decisions and sharper rotation discipline.",
  },
  {
    gameId: "den-phx-demo",
    status: "scheduled",
    tipoff: "10:00 PM ET",
    broadcast: "TNT",
    arena: "Footprint Center",
    headline: "Jokic hub offense against midrange shotmaking and late-switch counters.",
    homeTeam: "Phoenix Suns",
    awayTeam: "Denver Nuggets",
    homeAbbreviation: "PHX",
    awayAbbreviation: "DEN",
    homeRecord: "45-37",
    awayRecord: "54-28",
    predictionHook:
      "Denver's cutting and post facilitation create the biggest coaching stress test on the slate.",
  },
];

export const mockPreview: GamePreview = {
  gameId: "gsw-dal-demo",
  status: "scheduled",
  tipoff: "7:30 PM ET",
  broadcast: "ESPN",
  arena: "Chase Center",
  headline: "Ball-screen chess between Luka's usage and Kerr's coverage counters.",
  homeTeam: {
    teamId: "gsw",
    teamName: "Golden State Warriors",
    coachName: "Steve Kerr",
    offensiveRating: 117.3,
    defensiveRating: 113.9,
    pace: 101.4,
    threePointRate: 0.47,
    benchDepth: 0.58,
  },
  awayTeam: {
    teamId: "dal",
    teamName: "Dallas Mavericks",
    coachName: "Jason Kidd",
    offensiveRating: 118.9,
    defensiveRating: 114.8,
    pace: 99.8,
    threePointRate: 0.43,
    benchDepth: 0.51,
  },
  playersToWatch: [
    {
      playerId: "luka",
      playerName: "Luka Doncic",
      teamId: "dal",
      usageRate: 0.39,
      momentumScore: 0.68,
      fatigueIndex: 0.14,
      matchupDifficulty: 0.44,
    },
    {
      playerId: "kai",
      playerName: "Kyrie Irving",
      teamId: "dal",
      usageRate: 0.28,
      momentumScore: 0.61,
      fatigueIndex: 0.12,
      matchupDifficulty: 0.49,
    },
    {
      playerId: "steph",
      playerName: "Stephen Curry",
      teamId: "gsw",
      usageRate: 0.31,
      momentumScore: 0.62,
      fatigueIndex: 0.12,
      matchupDifficulty: 0.58,
    },
    {
      playerId: "jimmy",
      playerName: "Jimmy Butler",
      teamId: "gsw",
      usageRate: 0.27,
      momentumScore: 0.55,
      fatigueIndex: 0.17,
      matchupDifficulty: 0.54,
    },
  ],
  gameFactors: ["pace pressure", "lineup staggering", "half-court shot creation", "weak-side help timing", "rest advantage"],
  predictionSummary:
    "Luka is the primary leverage point. BallPredict expects Steve Kerr to adjust shell help, screen coverage, and rotation staggering around that usage load.",
};

export const mockSnapshot: Snapshot = {
  gameId: "gsw-dal-demo",
  quarter: 0,
  clock: "12:00",
  homeTeam: {
    teamId: "gsw",
    teamName: "Golden State Warriors",
    finalScoreMean: 114,
    finalScoreCI: [107, 122],
    pace: 102.6,
    offensiveRating: 118.1,
    defensiveRating: 112.6,
    winProbability: 0.44,
    projectedScore: [29, 27, 28, 30],
  },
  awayTeam: {
    teamId: "dal",
    teamName: "Dallas Mavericks",
    finalScoreMean: 117,
    finalScoreCI: [111, 125],
    pace: 100.7,
    offensiveRating: 119.2,
    defensiveRating: 111.8,
    winProbability: 0.56,
    projectedScore: [29, 30, 28, 30],
  },
  playerProjections: completeMockRoster([
    {
      playerId: "luka",
      playerName: "Luka Doncic",
      teamId: "dal",
      rotationRole: "starter",
      momentumScore: 0.68,
      fatigueIndex: 0.14,
      defensivePressure: 0.66,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 31.8, assists: 9.4, rebounds: 8.2, threesMade: 3.6, turnovers: 4.1, usageRate: 0.35, fieldGoalPct: 0.51 } },
      adjustments: [
        {
          title: "Blitz Primary Action",
          side: "defense",
          trigger: "Luka is the primary high-usage initiator entering the game",
          explanation: "Golden State projects to send extra bodies to the ball if Luka wins the first quarter touch battle.",
          counters: ["trap at level", "weak-side tag", "scram switch on short roll"],
          impact: { field_goal_pct: -0.05, assists: 0.8, turnovers: 0.6 },
        },
        {
          title: "Shrink the Floor",
          side: "defense",
          trigger: "Paint pressure is bending the shell",
          explanation: "The Warriors are loading nail help and icing side pick-and-rolls to cut off downhill lanes.",
          counters: ["nail help", "ICE side pick-and-roll", "gap shrink"],
          impact: { field_goal_pct: -0.03, skip_pass_frequency: 0.08 },
        },
      ],
    },
    {
      playerId: "steph",
      playerName: "Stephen Curry",
      teamId: "gsw",
      rotationRole: "starter",
      momentumScore: 0.62,
      fatigueIndex: 0.12,
      defensivePressure: 0.58,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 28.7, assists: 6.8, rebounds: 4.6, threesMade: 4.8, turnovers: 3.2, usageRate: 0.31, fieldGoalPct: 0.47 } },
      adjustments: [
        {
          title: "Top-Lock Off-Ball Actions",
          side: "defense",
          trigger: "Movement shooting gravity is stretching help",
          explanation: "Dallas is top-locking off-ball screens and pre-switching larger bodies into movement actions.",
          counters: ["top-lock", "lock-and-trail", "pre-switch into pindown"],
          impact: { three_point_pct: -0.04, secondary_handler_usage: 0.05 },
        },
      ],
    },
    {
      playerId: "kai",
      playerName: "Kyrie Irving",
      teamId: "dal",
      rotationRole: "starter",
      momentumScore: 0.61,
      fatigueIndex: 0.12,
      defensivePressure: 0.54,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 25.3, assists: 5.7, rebounds: 4.1, threesMade: 2.9, turnovers: 2.5, usageRate: 0.28, fieldGoalPct: 0.49 } },
      adjustments: [],
    },
    {
      playerId: "klay",
      playerName: "Klay Thompson",
      teamId: "dal",
      rotationRole: "starter",
      momentumScore: 0.46,
      fatigueIndex: 0.13,
      defensivePressure: 0.47,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 16.1, assists: 2.3, rebounds: 3.8, threesMade: 3.1, turnovers: 1.7, usageRate: 0.19, fieldGoalPct: 0.44 } },
      adjustments: [],
    },
    {
      playerId: "gafford",
      playerName: "Daniel Gafford",
      teamId: "dal",
      rotationRole: "starter",
      momentumScore: 0.42,
      fatigueIndex: 0.14,
      defensivePressure: 0.43,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 12.2, assists: 1.4, rebounds: 8.9, threesMade: 0, turnovers: 1.5, usageRate: 0.15, fieldGoalPct: 0.63 } },
      adjustments: [],
    },
    {
      playerId: "washington",
      playerName: "P.J. Washington",
      teamId: "dal",
      rotationRole: "starter",
      momentumScore: 0.45,
      fatigueIndex: 0.12,
      defensivePressure: 0.46,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 13.4, assists: 2.1, rebounds: 6.7, threesMade: 2.2, turnovers: 1.8, usageRate: 0.17, fieldGoalPct: 0.45 } },
      adjustments: [],
    },
    {
      playerId: "jimmy",
      playerName: "Jimmy Butler",
      teamId: "gsw",
      rotationRole: "starter",
      momentumScore: 0.55,
      fatigueIndex: 0.17,
      defensivePressure: 0.52,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 21.9, assists: 5.1, rebounds: 6.4, threesMade: 1.0, turnovers: 2.4, usageRate: 0.27, fieldGoalPct: 0.48 } },
      adjustments: [],
    },
    {
      playerId: "draymond",
      playerName: "Draymond Green",
      teamId: "gsw",
      rotationRole: "starter",
      momentumScore: 0.47,
      fatigueIndex: 0.16,
      defensivePressure: 0.41,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 9.3, assists: 7.1, rebounds: 7.8, threesMade: 1.1, turnovers: 2.6, usageRate: 0.17, fieldGoalPct: 0.47 } },
      adjustments: [],
    },
    {
      playerId: "podz",
      playerName: "Brandin Podziemski",
      teamId: "gsw",
      rotationRole: "starter",
      momentumScore: 0.44,
      fatigueIndex: 0.12,
      defensivePressure: 0.39,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 11.7, assists: 4.4, rebounds: 5.6, threesMade: 1.9, turnovers: 1.7, usageRate: 0.16, fieldGoalPct: 0.46 } },
      adjustments: [],
    },
    {
      playerId: "hield",
      playerName: "Buddy Hield",
      teamId: "gsw",
      rotationRole: "starter",
      momentumScore: 0.49,
      fatigueIndex: 0.11,
      defensivePressure: 0.40,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 14.6, assists: 2.0, rebounds: 3.4, threesMade: 3.4, turnovers: 1.5, usageRate: 0.18, fieldGoalPct: 0.45 } },
      adjustments: [],
    },
    {
      playerId: "looney",
      playerName: "Kevon Looney",
      teamId: "gsw",
      momentumScore: 0.34,
      fatigueIndex: 0.12,
      defensivePressure: 0.28,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 6.1, assists: 1.7, rebounds: 6.8, threesMade: 0, turnovers: 0.9, usageRate: 0.09, fieldGoalPct: 0.57 } },
      adjustments: [],
    },
    {
      playerId: "moody",
      playerName: "Moses Moody",
      teamId: "gsw",
      momentumScore: 0.36,
      fatigueIndex: 0.11,
      defensivePressure: 0.30,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 7.8, assists: 1.2, rebounds: 2.9, threesMade: 1.5, turnovers: 0.8, usageRate: 0.1, fieldGoalPct: 0.44 } },
      adjustments: [],
    },
    {
      playerId: "kuminga",
      playerName: "Jonathan Kuminga",
      teamId: "gsw",
      momentumScore: 0.4,
      fatigueIndex: 0.11,
      defensivePressure: 0.35,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 10.2, assists: 1.8, rebounds: 4.1, threesMade: 0.7, turnovers: 1.3, usageRate: 0.12, fieldGoalPct: 0.48 } },
      adjustments: [],
    },
    {
      playerId: "santos",
      playerName: "Gui Santos",
      teamId: "gsw",
      momentumScore: 0.28,
      fatigueIndex: 0.1,
      defensivePressure: 0.2,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 4.4, assists: 0.8, rebounds: 2.5, threesMade: 0.6, turnovers: 0.6, usageRate: 0.06, fieldGoalPct: 0.43 } },
      adjustments: [],
    },
    {
      playerId: "spencer",
      playerName: "Pat Spencer",
      teamId: "gsw",
      momentumScore: 0.2,
      fatigueIndex: 0.09,
      defensivePressure: 0.18,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 2.1, assists: 1.0, rebounds: 1.1, threesMade: 0.2, turnovers: 0.5, usageRate: 0.03, fieldGoalPct: 0.4 } },
      adjustments: [],
    },
    {
      playerId: "post",
      playerName: "Quinten Post",
      teamId: "gsw",
      momentumScore: 0.22,
      fatigueIndex: 0.09,
      defensivePressure: 0.19,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 3.6, assists: 0.7, rebounds: 2.4, threesMade: 0.5, turnovers: 0.4, usageRate: 0.04, fieldGoalPct: 0.42 } },
      adjustments: [],
    },
    {
      playerId: "payton",
      playerName: "Gary Payton II",
      teamId: "gsw",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Coach's Decision",
      momentumScore: 0.1,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "jackson-davis",
      playerName: "Trayce Jackson-Davis",
      teamId: "gsw",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Coach's Decision",
      momentumScore: 0.1,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "waters",
      playerName: "Lindy Waters III",
      teamId: "gsw",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Inactive",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "slomo",
      playerName: "Kyle Anderson",
      teamId: "gsw",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Inactive",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "marshall",
      playerName: "Naji Marshall",
      teamId: "dal",
      momentumScore: 0.35,
      fatigueIndex: 0.11,
      defensivePressure: 0.31,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 8.6, assists: 1.7, rebounds: 4.2, threesMade: 0.9, turnovers: 1.0, usageRate: 0.1, fieldGoalPct: 0.46 } },
      adjustments: [],
    },
    {
      playerId: "lively",
      playerName: "Dereck Lively II",
      teamId: "dal",
      momentumScore: 0.31,
      fatigueIndex: 0.12,
      defensivePressure: 0.28,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 7.9, assists: 1.2, rebounds: 6.4, threesMade: 0, turnovers: 0.9, usageRate: 0.09, fieldGoalPct: 0.62 } },
      adjustments: [],
    },
    {
      playerId: "hardy",
      playerName: "Jaden Hardy",
      teamId: "dal",
      momentumScore: 0.29,
      fatigueIndex: 0.1,
      defensivePressure: 0.25,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 6.4, assists: 1.3, rebounds: 1.9, threesMade: 1.1, turnovers: 0.8, usageRate: 0.08, fieldGoalPct: 0.43 } },
      adjustments: [],
    },
    {
      playerId: "powell",
      playerName: "Dwight Powell",
      teamId: "dal",
      momentumScore: 0.21,
      fatigueIndex: 0.1,
      defensivePressure: 0.2,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 3.1, assists: 0.8, rebounds: 2.6, threesMade: 0, turnovers: 0.5, usageRate: 0.04, fieldGoalPct: 0.55 } },
      adjustments: [],
    },
    {
      playerId: "martin",
      playerName: "Caleb Martin",
      teamId: "dal",
      momentumScore: 0.27,
      fatigueIndex: 0.1,
      defensivePressure: 0.24,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 5.9, assists: 1.1, rebounds: 3.3, threesMade: 1.0, turnovers: 0.7, usageRate: 0.07, fieldGoalPct: 0.42 } },
      adjustments: [],
    },
    {
      playerId: "dinwiddie",
      playerName: "Spencer Dinwiddie",
      teamId: "dal",
      momentumScore: 0.3,
      fatigueIndex: 0.1,
      defensivePressure: 0.27,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 7.1, assists: 2.9, rebounds: 2.2, threesMade: 1.2, turnovers: 1.0, usageRate: 0.08, fieldGoalPct: 0.41 } },
      adjustments: [],
    },
    {
      playerId: "exum",
      playerName: "Dante Exum",
      teamId: "dal",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Injury Management",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "christie",
      playerName: "Max Christie",
      teamId: "dal",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Coach's Decision",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "omax",
      playerName: "Olivier-Maxence Prosper",
      teamId: "dal",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Coach's Decision",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "lawson",
      playerName: "A.J. Lawson",
      teamId: "dal",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Inactive",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
    {
      playerId: "edwards",
      playerName: "Kessler Edwards",
      teamId: "dal",
      availabilityStatus: "dnp",
      rotationRole: "dnp",
      dnpReason: "Inactive",
      momentumScore: 0.08,
      fatigueIndex: 0.08,
      defensivePressure: 0,
      liveStats: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0 },
      projectedStats: { mean: { points: 0, assists: 0, rebounds: 0, threesMade: 0, turnovers: 0, usageRate: 0, fieldGoalPct: 0 } },
      adjustments: [],
    },
  ]),
  insights: [
    {
      title: "Primary Defensive Shift",
      body: "BallPredict expects Dallas's primary creation burden to trigger more help-side pressure and push the offense toward corner and slot kickout creation.",
      severity: "warning",
    },
    {
      title: "Fatigue Watch",
      body: "Lead creators are carrying above-normal touch loads, which raises turnover variance in late-clock possessions.",
      severity: "info",
    },
    {
      title: "Bench Leverage Edge",
      body: "Golden State's second unit projects better defensively if the game slows into half-court possessions.",
      severity: "advantage",
    },
  ],
  possessionFeed: [
    { quarter: 1, clock: "12:00", summary: "Pregame modeling expects Golden State to ICE side pick-and-rolls and crowd the nail early.", leverage: "high" },
    { quarter: 2, clock: "08:30", summary: "Dallas counters with ghost screens to drag the low man away and reopen slot passing windows.", leverage: "medium" },
    { quarter: 4, clock: "04:10", summary: "A projected scram switch package protects smaller guards during closing mismatch hunts.", leverage: "medium" },
  ],
  winProbabilitySeries: [
    { minute: 0, home: 0.53, away: 0.47 },
    { minute: 4, home: 0.5, away: 0.5 },
    { minute: 8, home: 0.46, away: 0.54 },
    { minute: 12, home: 0.42, away: 0.58 },
    { minute: 16, home: 0.45, away: 0.55 },
    { minute: 20, home: 0.44, away: 0.56 },
    { minute: 24, home: 0.44, away: 0.56 },
    { minute: 28, home: 0.47, away: 0.53 },
    { minute: 32, home: 0.49, away: 0.51 },
    { minute: 36, home: 0.46, away: 0.54 },
    { minute: 40, home: 0.43, away: 0.57 },
    { minute: 44, home: 0.44, away: 0.56 },
    { minute: 48, home: 0.44, away: 0.56 },
  ],
};

export const mockPlayerDetail: PlayerDetail = {
  gameId: "gsw-dal-demo",
  playerId: "luka",
  playerName: "Luka Doncic",
  teamId: "dal",
  teamName: "Dallas Mavericks",
  opponentTeamName: "Golden State Warriors",
  coachCounterSummary:
    "Steve Kerr is the most likely coach to bend coverages around Luka, changing help location, ball-screen coverage, and late-clock matchup assignments.",
  projection: mockSnapshot.playerProjections[0],
  quarterBreakdown: [
    { quarter: "Q1", points: 8.6, assists: 2.1, rebounds: 2.0, threesMade: 1.0 },
    { quarter: "Q2", points: 7.2, assists: 2.0, rebounds: 1.8, threesMade: 0.8 },
    { quarter: "Q3", points: 7.8, assists: 2.4, rebounds: 2.0, threesMade: 0.9 },
    { quarter: "Q4", points: 8.2, assists: 2.9, rebounds: 2.4, threesMade: 0.9 },
  ],
  statProfile: [
    { label: "Points", live: 0, projected: 31.8 },
    { label: "Assists", live: 0, projected: 9.4 },
    { label: "Rebounds", live: 0, projected: 8.2 },
    { label: "3PM", live: 0, projected: 3.6 },
    { label: "Turnovers", live: 0, projected: 4.1 },
  ],
  matchupFactors: [
    "Usage load at 35%",
    "Golden State defensive rating 113.9",
    "Jason Kidd pace baseline 99.8",
    "weak-side help timing",
    "rotation staggering leverage",
  ],
  confidence: {
    floorPoints: 25.9,
    medianPoints: 31.8,
    ceilingPoints: 38.7,
    pressure: 0.66,
  },
  playerInsights: [
    {
      title: "Scoring Shape",
      body: "Luka's projection is fueled by heavy on-ball creation and early-clock paint touches that create both pull-ups and collapse-driven kickouts.",
      severity: "advantage",
    },
    {
      title: "Defensive Response",
      body: "Golden State is expected to change help position and screen coverage if Luka opens efficiently and controls first-action possessions.",
      severity: "warning",
    },
    {
      title: "Playmaking Spillover",
      body: "Extra pressure on the ball lowers pure scoring efficiency a bit, but it raises assist equity and weak-side chance creation.",
      severity: "info",
    },
  ],
};
